#!/usr/bin/env bash

# mvn versions:set-property -Dproperty=revision -DnewVersion

DOCKER=${DOCKER:-}

OUT_DIR=${OUT_DIR:-}
REPO_URL=${REPO_URL:-}
CALCITE_URL=${CALCITE_URL:-}
RUN_BASH=${RUN_BASH:-}
BUILD_ARGS=${BUILD_ARGS:-}
BRANCH=${BRANCH:-}
CALCITE_BRANCH=${CALCITE_BRANCH:-}
PKG_ARCH=${PKG_ARCH:-rpm}
PROJECT_DIR=${PROJECT_DIR:-}
VER_MAIN=${VER_MAIN:-}
VER_BUILD=${VER_BUILD:-}
PKG_EXTENSION=${PKG_EXTENSION:-rpm}
VER_S=${VER_S:-}
VER=${VER:-}
OUT_PKG_DIR=/tmp/compiled
PROJECT=${PROJECT:-}


CALCITE_REPO_DIR=calcite

git config --global user.email "me@nxa.io"
git config --global user.name "BuilderBot"

help(){
  cmd_list=`typeset -f|grep '()'|cut -d ' ' -f 1|grep -v "__"|grep -v "help"`
  echo -e "Available commands: \n ${cmd_list}"
}

switch_branch(){
 pushd ${PROJECT_DIR}
  read -p "Branch name switch to:" branch_name
  if [[ -z ${branch_name} ]]; then
    echo "Cancelling, no branch selected"
    return
  fi

  echo "Reset current branch state..."
  git reset --hard HEAD 1>/dev/null 2>&1

  echo "Clean git tree..."
  git clean -fd 1>/dev/null 2>&1

  echo "Trying to checkout to ${branch_name}.."
  git checkout ${branch_name} 1>/dev/null 2>&1

  if [ $? -nq 0 ]; then  # do not replace to double squared brackets
    echo "Fail to checkout, verify branch name"
  else
    echo "done"
  fi

 popd
}

upload-files(){
 set -f  # disable asterisk expansion by bash (glob)

 rm -rf ${OUT_PKG_DIR}
 mkdir ${OUT_PKG_DIR}

 # ToDo: move to configuration?
 EXCLUDE_FOLDERS="common contrib docs drill-shaded drill-yarn exec logical protocol sample-data"
 EXCLUDE_FOLDERS_FORMATED=

 for i in ${EXCLUDE_FOLDERS}; do
   EXCLUDE_FOLDERS_FORMATED="${EXCLUDE_FOLDERS_FORMATED} -not -path */${i}/*"
 done

 find ${PROJECT_DIR} -name "*.${PKG_EXTENSION}" ${EXCLUDE_FOLDERS_FORMATED} -exec cp -f {} ${OUT_PKG_DIR} \;

 set +f

 echo " ==> Uploading files to bucket \"${BRANCH}\""
 FILES=${OUT_PKG_DIR}/*
 for i in ${FILES}; do
   storage put ${BRANCH} ${i}
 done
}


build(){
 echo =======================================================
 echo Building version "${VER}"
 echo =======================================================
 pushd /root  >/dev/null 2>&1

    download-project

   build-project
   upload-files
 popd
}

build-calcite(){
  local arg=$1
  local do_install=0

  if [[ "x${arg}" == "xinstall" ]]; then
    local do_install=1
  fi

  echo =======================================================
  echo Building branch "${CALCITE_BRANCH}"
  echo =======================================================
  pushd /root  >/dev/null 2>&1
    download-calcite
    if [[ ${do_install} -eq 0 ]]; then
      build-calcite
    else
      mvn-install-calcite
    fi
  popd
}

load-supported-modules(){
  local modules_to_add=""
  echo ${modules_to_add}| tr ';' '\n'|while read item; do
    if [[ -d "${PROJECT_DIR}/${item}" ]]; then
      echo -n "${item},"
    fi
  done
}

update-repo(){
 download-project
 pushd ${PROJECT_DIR} 1>/dev/null 2>&1
   git pull
 popd 1>/dev/null 2>&1
}

build-project(){
  download-project
  pushd ${PROJECT_DIR} 1>/dev/null 2>&1
#  mvn versions:set -DnewVersion=${VER}

  mvn package -DskipTests

  popd 1>/dev/null 2>&1
}

build-calcite(){
  download-calcite
  pushd ${CALCITE_REPO_DIR} 1>/dev/null 2>&1
    mvn package -DskipTests
  popd 1>/dev/null 2>&1
}

mvn-install-calcite(){
  download-calcite
  pushd ${CALCITE_REPO_DIR} 1>/dev/null 2>&1
    mvn install -DskipTests
  popd 1>/dev/null 2>&1
}


__clone_repo(){
  local folder=$1
  local repo_url=$2
  local project_dir=$3
  local branch=$4
  git clone ${repo_url} ${folder}/

  if [[ $? -ne 0 ]]; then
    return 1
  fi

  pushd ${project_dir}  1>/dev/null 2>&1
    git checkout ${branch}

    if [[ $? -ne 0 ]]; then
      return 1
    fi

  popd 1>/dev/null 2>&1
}

__download_repo(){
  local folder=$1
  local repo_url=$2
  local project_dir=$3
  local branch=$4

  pushd /root  1>/dev/null 2>&1
    # drill repo
    ls ${project_dir}/.git 1>/dev/null 2>&1

    if [[ $? -ne 0 ]]; then
      echo -n "--> Downloading ${project_dir} repo and checking out ${branch}..."
      __clone_repo "${folder}" "${repo_url}" "${project_dir}" "${branch}"
      if [[ $? -ne 0 ]]; then
        echo "Fail"
        return 1
      else
        echo "ok"
      fi
    fi
  popd >/dev/null 2>&1
}


clone-project-repo(){
 __clone_repo "project" "${REPO_URL}" "${PROJECT_DIR}" "${BRANCH}"
}

clone-calcite-repo(){
  __clone_repo "${CALCITE_REPO_DIR}" "${CALCITE_URL}" "${CALCITE_REPO_DIR}" "${CALCITE_BRANCH}"
}


download-project(){
  __download_repo "project" "${REPO_URL}" "${PROJECT_DIR}" "${BRANCH}"
}

download-calcite(){
  __download_repo "${CALCITE_REPO_DIR}" "${CALCITE_URL}" "${CALCITE_REPO_DIR}" "${CALCITE_BRANCH}"
}

test-project(){
download-project
pushd "${PROJECT_DIR}"
  mvn package
popd
}
